# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: mysite/familytree/templates/familytree/email/
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--extend-select", "I"]
