# Generated by Django 3.0.3 on 2020-02-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('marriage_date_string', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('display_name', models.CharField(max_length=40)),
                ('dob_string', models.CharField(blank=True, default='', max_length=30)),
                ('origin_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.Family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='partner1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner1', to='familytree.Person'),
        ),
        migrations.AddField(
            model_name='family',
            name='partner2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner2', to='familytree.Person'),
        ),
    ]
