# Generated by Django 3.2.8 on 2021-10-31 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_indi', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('display_name', models.CharField(blank=True, max_length=75)),
                ('wife_indi', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('husband_indi', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('child_indi', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('no_kids_bool', models.BooleanField(null=True)),
                ('original_family', models.BooleanField(null=True)),
                ('original_family_text', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('direct_family_number', models.IntegerField(blank=True, null=True)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('marriage_date_note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('divorced', models.BooleanField(default=False, null=True)),
                ('show_on_branch_view', models.BooleanField(default=False, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('notes1', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('notes2', models.CharField(blank=True, default='', max_length=600, null=True)),
                ('branch_seq', models.IntegerField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='familytree.Branch')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_name', models.CharField(blank=True, max_length=50, null=True)),
                ('med_name', models.CharField(blank=True, max_length=50, null=True)),
                ('little_name', models.CharField(blank=True, max_length=50, null=True)),
                ('caption', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('spouses_only', models.BooleanField(default=False, null=True)),
                ('featured', models.IntegerField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='familytree.Branch')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to='familytree.family')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_indi', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('gedcom_uuid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('first', models.CharField(blank=True, default='', max_length=30)),
                ('middle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('last', models.CharField(blank=True, default='', max_length=20)),
                ('maiden', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('display_name', models.CharField(max_length=40, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_note', models.CharField(blank=True, default='', max_length=55, null=True)),
                ('birthyear', models.IntegerField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('orig_fam_indi', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('sex', models.CharField(default='', max_length=2)),
                ('origin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('face', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('current_location', models.CharField(blank=True, default='', max_length=75, null=True)),
                ('work', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('interests', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('education', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('death_place', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('deathdate', models.DateField(blank=True, null=True)),
                ('deathdate_note', models.CharField(blank=True, default='', max_length=175, null=True)),
                ('hidden', models.BooleanField(default=False, null=True)),
                ('adopted', models.BooleanField(default=False, null=True)),
                ('direct_line', models.BooleanField(default=False, null=True)),
                ('show_on_landing_page', models.BooleanField(default=False, null=True)),
                ('sibling_seq', models.IntegerField(blank=True, null=True)),
                ('notes1', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('notes2', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('notes3', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('flag1', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('flag2', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('flag3', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('reviewed', models.BooleanField(default=False, null=True)),
                ('living', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='familytree.Branch')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.family')),
            ],
            options={
                'verbose_name_plural': 'People',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, to='familytree.Branch')),
                ('family', models.ManyToManyField(blank=True, to='familytree.Family')),
                ('person', models.ManyToManyField(blank=True, to='familytree.Person')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vid_person_id', to='familytree.person')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_id', to='familytree.video')),
            ],
            options={
                'verbose_name_plural': 'VideoPerson records',
                'db_table': 'person_video',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('intro', models.CharField(blank=True, max_length=2000, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dashboard_feature', models.BooleanField(default=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='familytree.Branch')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_count', models.IntegerField(default=0, null=True)),
                ('last_pestered', models.DateField(blank=True, null=True)),
                ('connection_notes', models.CharField(blank=True, max_length=250, null=True)),
                ('furthest_html', models.CharField(blank=True, max_length=250, null=True)),
                ('shared_account', models.BooleanField(default=False, null=True)),
                ('guest_user', models.BooleanField(default=False)),
                ('limited', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='US/Eastern', max_length=100, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='familytree.Branch')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='PersonStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.person')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.story')),
            ],
            options={
                'verbose_name_plural': 'PersonStory records',
                'db_table': 'person_story',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=50, null=True)),
                ('external_author', models.BooleanField(default=False, null=True)),
                ('body', models.CharField(max_length=3000)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('for_self', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='familytree.person')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_note', to='familytree.family')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_person', to='familytree.person')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='ImagePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_id', to='familytree.image')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_id', to='familytree.person')),
            ],
            options={
                'verbose_name_plural': 'ImagePerson records',
                'db_table': 'image_person',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='familytree.person'),
        ),
        migrations.CreateModel(
            name='FamilyStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.family')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familytree.story')),
            ],
            options={
                'verbose_name_plural': 'FamilyStory records',
                'db_table': 'family_story',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='husband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner2', to='familytree.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='wife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner1', to='familytree.person'),
        ),
        migrations.CreateModel(
            name='Audiofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=150, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, to='familytree.Branch')),
                ('person', models.ManyToManyField(blank=True, to='familytree.Person')),
            ],
            options={
                'db_table': 'audiofiles',
            },
        ),
    ]
