# Generated by Django 3.0.3 on 2020-02-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_auto_20200222_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='marriage_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
