# Generated by Django 3.0.3 on 2020-02-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0004_auto_20200222_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='caption',
            new_name='display_name',
        ),
    ]
