# Generated by Django 3.2 on 2021-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0006_videoperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoperson',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
