# Generated by Django 3.2 on 2021-06-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0016_note_external_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guest_user',
            field=models.BooleanField(default=False),
        ),
    ]
