# Generated by Django 3.2 on 2021-07-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0017_profile_guest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
    ]
