# Generated by Django 3.2 on 2021-07-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("familytree", "0018_remove_profile_last_login")]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="logins", new_name="login_count"
        )
    ]
