# Generated by Django 3.2 on 2021-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("familytree", "0019_rename_logins_profile_login_count")]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "logins", "managed": False},
        )
    ]
