# Generated by Django 3.2 on 2021-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("familytree", "0020_login")]

    operations = [
        migrations.AlterField(
            model_name="family",
            name="child_indi",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="gedcom_indi",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="husband_indi",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="family",
            name="wife_indi",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="gedcom_indi",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="orig_fam_indi",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
