# Generated by Django 3.2 on 2021-07-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("familytree", "0022_alter_family_display_name")]

    operations = [
        migrations.AddField(
            model_name="story",
            name="branches",
            field=models.ManyToManyField(blank=True, to="familytree.Branch"),
        )
    ]
