# Generated by Django 3.2 on 2021-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("familytree", "0025_alter_note_date")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="limited",
            field=models.BooleanField(default=True),
        )
    ]
