    [tool.ruff]
    line-length = 120
    target-version = "py312" # Adjust to your Python version

    [tool.ruff.lint]
    select = ["E", "F", "I"] # E: pycodestyle, F: pyflakes, I: isort
    ignore = ["E722", "F811"] # Allow bare except for now, and redefinition (of logout)
