# Generated by Django 3.2 on 2021-04-21 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("familytree", "0008_familystory")]

    operations = [migrations.AlterModelTable(name="videoperson", table="person_video")]
