# Generated by Django 3.2 on 2021-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("familytree", "0009_alter_videoperson_table")]

    operations = [
        migrations.AlterField(
            model_name="videoperson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        )
    ]
