# Generated by Django 3.2 on 2021-04-25 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("familytree", "0012_branch_branch_grandparent_id")]

    operations = [migrations.RemoveField(model_name="branch", name="branch_grandparent_id")]
