# Generated by Django 3.2 on 2021-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("familytree", "0028_image_notes")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="parents_only",
            field=models.BooleanField(default=False, null=True),
        )
    ]
